algoritmo "semnome"
// Função :
// Autor :
// Data : 25/01/2022
// Seção de Declarações 
var
 nome, mes: caractere
 salario: real
inicio
// Seção de Comandos
EScreval ("Digite o nome do funcionário: ")
Leia (nome)
EScreval ("Digite o salário do funcionário: R$")
Leia (salario)
Escreval ( "Digite o mês: ")
leia (mes)
Escreva ( " O(a) funcionário(a), " , nome, ", tem um salário de R$" , salario:7:2 , " em " , mes)
fimalgoritmo
