algoritmo "semnome"
// Função :
// Autor :
// Data : 04/02/2022
// Seção de Declarações 
var
mat: vetor[1..3, 1..2] de inteiro
l, c: inteiro
inicio
// Seção de Comandos
Para l <- 1 ate 3 faca
     Para c <- 1 ate 2 faca
          escreva ("Digite o valor da posição [", l, "," , c, "] : ")
          leia (mat[l,c])
     FimPara
FimPara

Para l <- 1 ate 3 faca
     Para c <- 1 ate 2 faca
          Escreva (mat[l,c]:5)
     FimPara
     EscrevaL ()
FimPara
fimalgoritmo
