algoritmo "Condicional_Aninhada"
// Função :
// Autor :
// Data : 21/01/2022
// Seção de Declarações 
var
   dinheiro: real
inicio
// Seção de Comandos 
escreval(" Quanto em dinheiro voce juntou? ")
leia (dinheiro)
Se (dinheiro >= 10000) entao
   escreval ( "partiu Disney")
Senao
     Se (dinheiro >= 5000) e (dinheiro < 10000) entao
        EScreval (" visitar familia ")
     Senao
         escreva (" Vai ficar em casa!" )
     FimSe

FimSe



fimalgoritmo
