algoritmo "semnome"
// Função :
// Autor :
// Data : 21/01/2022
// Seção de Declarações 
var
N1, N2, M: real

inicio
// Seção de Comandos
Escreval (" digite a primeira nota: ")
Leia (N1)
Escreval ("escreva a segunda nota: ")
Leia (N2)
 M <- (N1 + N2) / 2
 Se M >= 7 entao
    EScreval (" voce esta aprovado ")
 Senao
    EScreva (" Voce esta reprovado ")
 FimSe

 
fimalgoritmo
