algoritmo "semnome"
// Função :
// Autor :
// Data : 24/01/2022
// Seção de Declarações 
var
 comeco, fim: inteiro

inicio
// Seção de Comandos

EScreva ("qual o inicio? ")
Leia (comeco)
Escreva ("qual o Fim? ")
Leia (fim)

Enquanto (comeco <> fim) faca

         SE (comeco < fim) entao
           Escreva (comeco)
          comeco <- comeco + 1
        SEnao
          Escreva (fim)
          fim <- fim - 1
         FimSE
         


FimEnquanto

fimalgoritmo
