algoritmo "semnome"
// Função :
// Autor :
// Data : 21/01/2022
// Seção de Declarações 
var
contador, valor, salto: inteiro

inicio
// Seção de Comandos 
Contador <- 0
EScreva ("Quer contar até quanto? ")
Leia (valor)
EScreva (" Qual será o valor do salto? ")
leia (salto)
Enquanto (contador <= valor) faca
   Escreval (contador)
   contador <- contador + salto
FimEnquanto
Escreval ("terminei de contar")

fimalgoritmo
