algoritmo "Função_SOMA"
// Função :
// Autor :
// Data : 02/02/2022
// Seção de Declarações 

var
V1, V2, S: Inteiro
funcao Soma (X, Y: Inteiro) : Inteiro
inicio
      Retorne X + Y
FimFuncao

inicio
// Seção de Comandos 
escreva("Digite um valor: ")
Leia (V1)
escreva("Digite outro valor: ")
Leia (V2)
S <- Soma(V1, V2)
EScreva ("A soma entre ", V1, " e ", V2, " é igual a ", S)
fimalgoritmo
