algoritmo "Creuza01"
// Função :
// Autor :
// Data : 20/01/2022
// Seção de Declarações 
var
     ano_atual, ano_nascimento, Idade: inteiro

inicio
// Seção de Comandos 
     EScreval ("Em que ano nós estamos? ")
     Leia (ano_atual)
     Escreval ("Em que ano eu nasci? ")
     Leia (ano_nascimento)
     Idade <- ano_atual - ano_nascimento
     EScreva ("Minha idade é " , Idade)
     


fimalgoritmo
