algoritmo "semnome"
// Função :
// Autor :
// Data : 31/01/2022
// Seção de Declarações 
var
C, V, Tot010: inteiro
inicio
// Seção de Comandos
Tot010 <- 0
Para C <- 1 ate 6 faca
     escreva ("Digite um valor: ")
     Leia (v)
     Se (V >= 0) e (V <= 10)entao
        Tot010 <- Tot010 + 1
     FimSe
FimPara
EScrevaL ("Ao todo foram ", Tot010," valores entre 0 e 10")
     
     
     
fimalgoritmo
