algoritmo "semnome"
// Função :
// Autor :
// Data : 01/02/2022
// Seção de Declarações 
var
X, Y: inteiro
procedimento Soma(A, B: inteiro)
inicio
      A <- A + 1
      B <- B + 2
      escreval("Valor de A = ", A)
      escreval ("Valor de B = ", B)
      escreval("A soma de A + B = ", A+B)
FimProcedimento
inicio
// Seção de Comandos 
X <- 4
Y <- 8
Soma (X, Y)
escrevaL ("Valor de X = ", X)
escrevaL ("Valor de Y = ", Y)
fimalgoritmo
