algoritmo "semnome"
// Função :
// Autor :
// Data : 28/01/2022
// Seção de Declarações 
var
Pn, UN, S, contador: inteiro
inicio
// Seção de Comandos
escreva ("Digite o primeiro numero: ")
leia (PN)
escreva ("Digite o ultimo numero: ")
leia (UN)
escreva ("Digite o valor do salto: ")
leia (S)
Contador <- PN
enquanto (contador >= PN) e (contador <= UN) faca
         escreva (contador)
         Contador <- contador + S
fimEnquanto
escreval (" Acabou!")

fimalgoritmo
