algoritmo "semnome"
// Função :
// Autor :
// Data : 26/01/2022
// Seção de Declarações 
var
L1, L2, L3: real
inicio
// Seção de Comandos
escreval (" Digite o primeiro numero: ")
leia (L1)
escreval (" Digite o segundo numero: ")
leia (L2)
escreval (" Digite o terceiro numero: ")
leia (L3)
SE (L1 < (L2 + L3)) e (L2 < (L1+ L3)) e (L3 < (L1 + L2)) entao
   EScreval (" Forma um triangulo!")
senao
   EScreval (" Não forma um triangulo!")

FimSe

fimalgoritmo
