algoritmo "semnome"
// Função :
// Autor :
// Data : 25/01/2022
// Seção de Declarações 
var
A, L, AreaTotal, Tinta: real
inicio
// Seção de Comandos
EScreval ( "Qual a altura da parede? ")
Leia (A)
Escreval (" Qual a largura da parede? ")
Leia (L)
AreaTotal <- A * L
Tinta <- AreaTotal / 2
EScreval(" A area total de " , AreaTotal, " metros quadrados irá necessitar de")
escreval (Tinta , " litros de tinta para pintar toda a área indicada")
fimalgoritmo
