algoritmo "semnome"
// Função :
// Autor :
// Data : 28/01/2022
// Seção de Declarações 
var
contador, salto, soma: inteiro
inicio
// Seção de Comandos
Contador <- 6
Salto <- 2
soma <- 0

enquanto (contador <= 10) faca
         escreval (contador, " + ")
         soma <- soma + contador
         contador <- contador + salto
FimEnquanto
escreval ("A soma de todos os números é igual a: " , soma)



fimalgoritmo
