algoritmo "semnome"
// Função :
// Autor :
// Data : 26/01/2022
// Seção de Declarações 
var
nome: caractere
DT, Valor_hora: real

inicio
// Seção de Comandos 
escreva (" Digite o nome do funcionário: ")
Leia (nome)
EScreval ("Quantos dias o funcionário trabalhou no mês? ")
Leia (DT)
DT <- DT*8
Valor_hora <- DT*25
EScreva (" O(a) Funcionário(a) ", nome , " irá receber o salário de: R$" , Valor_hora)


fimalgoritmo
